### ISSUE TITLE
mz really needed?

### ISSUE THREAD

**Issue by LeoIannacone** [crypto-utils/uid-safe#1]
Hi,

is it really needed require 'mz/crypto' ??

I mean, could module be rewritten doing the same job without install extra 600KB dependencies ?

**Comment by dougwilson** [comment]
`mz` is way overkill on this lib and just broke a bunch of expressjs modules :) i would like to remove the dep, especially since we don't need it to keep our external API the same.

**Comment by jonathanong** [comment]
what broke?

**Comment by dougwilson** [comment]
It was then thenify-all lib, but the main reason I bring back up `mz` is not that I want to remove the promises, just that really, it seems weird that we'd implement the main function twice in the first place (i.e. if we used `Promise` directly instead of `mz`, we'd only need one implementation for the main function).

**Comment by jonathanong** [comment]
but we can't use `Promise` directly because no stable version of node supports it. unless you want to drop support for promises w/ them (i don't mind). ideally, yes, we'd use `Promise` directly though

**Comment by dougwilson** [comment]
well, by "promise directly" i just meant to depend on `native-or-bluebird`, which is what `mz` is already doing.

**Comment by jonathanong** [comment]
i'm okay with that too!

**Comment by dougwilson** [comment]
I was thinking like:
```js
function uid(length, callback) {
  if (callback) {
    return generateUid(length, callback)
  }

  if (!Promise) {
    Promise = require('native-or-bluebird')
  }

  return new Promise(function (resolve, reject) {
    generateUid(length, function (err, str) {
      if (err) return reject(err)
      resolve(str)
    })
  })
}
```

**Comment by jonathanong** [comment]
works for me

**Comment by jonathanong** [comment]
as long as the api stays the same it doesn't really matter

**Comment by dougwilson** [comment]
right. i would definitely _not_ change the API :)
