### ISSUE TITLE
Will uid-safe always return the specific length(after base64)?

### ISSUE THREAD

**Issue by jilvin** [crypto-utils/uid-safe#18]
I saw a portion in the source code where = at the end of the string after base64 is replaced with an empty string. If that's the case should a specific length return of generated uids expected?

**Comment by jilvin** [comment]
So I read a bit on base64. = is used to add padding so that the output always has a length that is a multiple of 4? If that's the case, we can expect a consistent length output for a specific byte length. I am just confirming. Correct me if I am wrong.

**Comment by dougwilson** [comment]
What this module is outputting is the base64url variant https://tools.ietf.org/html/rfc4648#section-5

**Comment by jilvin** [comment]
@dougwilson Thanks a lot. Will check it out. 🤗 👍
