### ISSUE TITLE
crypto.randomBytes

### ISSUE THREAD

**Issue by behrang** [crypto-utils/uid-safe#5]
As I read from node docs here: [http://nodejs.org/api/crypto.html#crypto_crypto_pseudorandombytes_size_callback](http://nodejs.org/api/crypto.html#crypto_crypto_pseudorandombytes_size_callback) it is stated that these may be predictable.

I think this module should use `crypto.randomBytes` instead.

**Comment by dougwilson** [comment]
It's unfortunate, but Node.js will throw randomly if using `crypto.randomBytes` until 0.12.

**Comment by dougwilson** [comment]
I can change the code, though, to try `randomBytes`, and if it errors/throws, use `pseudoRandomBytes` instead.

**Comment by jonathanong** [comment]
i highly doubt it would ever actually throw. i think that if and when we drop `0.10` support, we should switch to `.randomBytes()`

**Comment by dougwilson** [comment]
It throws when if you call `.sync()` and we call the sync version ;)

**Comment by jonathanong** [comment]
ya but it throws when you run out of entropy i believe... which i don't think people will hit very often

**Comment by jonathanong** [comment]
nice solution :)

**Comment by dougwilson** [comment]
Though I don't see how it's an issue (since, internally, `pseudoRandomBytes` is actually the same implementation as `randomBytes` if the pool has been seeded, using `pseudoRandomBytes` is bound to scare people looking at the source and comparing to Node.js documentation, rather than to the Node.js/OpenSSL source.

**Comment by dougwilson** [comment]
Here is a user who has nicely spelled it out: http://stackoverflow.com/questions/18130254/randombytes-vs-pseudorandombytes#answer-18131768

**Comment by behrang** [comment]
Thanks, anyway.

**Comment by dougwilson** [comment]
@behrang the next version will use `randomBytes` directly (look at the commit that closed this issue).

**Comment by behrang** [comment]
Yeah, I saw it. That was great.

**Comment by dougwilson** [comment]
@behrang OK, cool, sorry :) I thought the comment sounded like you went away unhappy, haha.

**Comment by behrang** [comment]
Sorry for the bad wording :)
