### ISSUE TITLE
Doc Improvement

### ISSUE THREAD

**Issue by Magnitus-** [crypto-utils/uid-safe#6]
In the doc:

"To use promises, you must define a global Promise if necessary."

Maybe it's obvious for readers already familiar with Promises (especially in the context of a Node.js environment), but for those new to it, a tad more details would be helpful.

The way it is phrased right now, it makes it seem as if you are expected to implement this yourself.

Something like this might be more helpful:

"To use promises, a global Promise variable must be defined in your environment. This is not the case for current versions of Node.js, but it can be achieved with a polyfill like the one in the es6-promise project."

**Comment by dougwilson** [comment]
Great, I agree! I'll get this done, but if you feel like submitting a PR, that would be great :)

**Comment by Magnitus-** [comment]
Sure, it's good practice. I'll get to figure out how to do a PR properly.
